config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users

  resources :failed_contacts, only: [:index]
  resources :csv_files, only: [:index]
  resources :contacts, only: [:index, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/contact_methods.rb
module ContactMethods
  extend ActiveSupport::Concern
  def last_four_digits
    decoded_token = JWT.decode(card_number, Rails.application.credentials[:secret_token], false,
                               { algorithm: 'HS256' })
    "****#{decoded_token[0]['credit_card_number'][-4..]}"
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  include ContactMethods
  attr_accessor :credit_card, :date_of_birth

  belongs_to :user
  validates :email, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
                              message: 'invalid email format' }
  validates :name, format: { with: /\A[a-zA-Z0-9\-]+\z/,
                             message: 'only alphanumeric or minus symbol are allowed' }
  validate :iso_8601_date_format
  validates :phone, format: { with: /\A\(\+[0-9]{2}\)(( [0-9]{3}){2}( [0-9]{2}){2}| ([0-9]{3}-){2}[0-9]{2}-[0-9]{2})\z/,
                              message: 'invalid phone format' }
  validate :valid_card_number
  validates :email, uniqueness: { scope: :user_id }
  validates_presence_of :name, :phone, :address, :email, :user_id

  def birth_human_date_format
    birth.stamp('1999 March 1')
  end

  private

  def iso_8601_date_format
    if date_format('%Y%m%d') || date_format('%F')
      self.birth = date_of_birth
    else
      errors.add(:date_of_birth, message: 'Should use ISO 8601 (%Y%m%d or %F) format')
    end
  end

  def date_format(format_)
    DateTime.strptime(date_of_birth, format_)
    true
  rescue StandardError
    false
  end

  def valid_card_number
    detector = CreditCardDetector::Detector.new(credit_card)
    brand_name = detector.brand.nil? ? detector.brand_name : detector.brand.id
    if brand_name.nil?
      errors.add(:credit_card, message: 'invalid credit card number')
    else
      self.franchise = brand_name
      self.card_number = JWT.encode({ credit_card_number: credit_card }, Rails.application.credentials[:secret_token],
                                    'HS256')
    end
  end
end

app/models/csv_file.rb
class CsvFile < ApplicationRecord
  include AASM
  belongs_to :user
  validates_presence_of :user_id
  has_one_attached :file
  validates :aasm_state, presence: true

  aasm do # default column: aasm_state
    state :on_hold, initial: true
    state :processing
    state :failed
    state :finished

    event :process do
      transitions from: :on_hold, to: :processing
    end

    event :fail do
      transitions from: :processing, to: :failed
    end

    event :finish do
      transitions from: %w[on_hold processing], to: :finished
    end
  end
end

app/models/failed_contact.rb
class FailedContact < ApplicationRecord
  include ContactMethods
  attr_accessor :credit_card

  belongs_to :user
  validates_presence_of :user_id
  validates_presence_of :error_message
  before_save :credit_card_info

  def credit_card_info
    detector = CreditCardDetector::Detector.new(credit_card)
    brand_name = detector.brand.nil? ? detector.brand_name : detector.brand.id
    self.franchise = brand_name unless brand_name.nil?
    self.card_number = JWT.encode({ credit_card_number: credit_card.nil? ? '' : credit_card },
                                  Rails.application.credentials[:secret_token], 'HS256')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :csv_files
  has_many :contacts
  has_many :failed_contacts
  validates_confirmation_of :password
  validates_presence_of :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pagy, @contacts = pagy(Contact.where(user_id: current_user.id))
  end

  def create
    uploaded_io = params[:file]
    if File.extname(uploaded_io) == '.csv'
      file = save_csv(uploaded_io)
      LoadContactsJob.perform_later(file, current_user.id)
      redirect_to new_contact_path, notice: 'Contacts successfully added'
    else
      redirect_to new_contact_path, alert: 'Only valid format is csv'
    end
  end

  private

  def save_csv(uploaded_io)
    id = CsvFile.create!(file: uploaded_io, filename: uploaded_io.original_filename, user_id: current_user.id).id
    CsvFile.find(id)
  end
end

app/controllers/csv_files_controller.rb
class CsvFilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @pagy, @files = pagy(CsvFile.where(user_id: current_user.id))
  end
end

app/controllers/failed_contacts_controller.rb
class FailedContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pagy, @contacts = pagy(FailedContact.where(user_id: current_user.id))
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/index.html.erb
<%== pagy_nav(@pagy)%>
<table>
  <thead>
    <tr>
      <th>Created at</th>
      <th>Name</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Credit card</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
      <td><%= contact.created_at %></td>
        <td><%= contact.name %></td>
        <td><%= contact.birth_human_date_format %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.last_four_digits %></td>
        <td><%= contact.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/new.html.erb
<%= form_tag("/contacts/", method: "post", multipart: true ) do %>
    <%= label_tag(:q, "Add contacts:") %><br><br>
    <%= file_field_tag(:file) %><br><br>
    <%= submit_tag("Upload file") %>
<% end %>

app/views/csv_files/index.html.erb
<%== pagy_nav(@pagy)%>
<table>
  <thead>
    <tr>
      <th>Uploaded at</th>
      <th>State</th>
      <th>Link donwload</th>
    </tr>
  </thead>

  <tbody>
    <% @files.each do |file| %>
      <tr>
        <td><%= file.created_at %></td>
        <td><%= file.aasm_state %></td>
        <td><%= link_to file.filename, rails_blob_path(file.file, disposition: 'attachment') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/failed_contacts/index.html.erb
<%== pagy_nav(@pagy)%>
<table>
  <thead>
    <tr>
      <th>Created at</th>
      <th>Name</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Credit card</th>
      <th>Email</th>
      <th>Errors</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.created_at %></td>
        <td><%= contact.name %></td>
        <td><%= contact.birth %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.last_four_digits %></td>
        <td><%= contact.email %></td>
        <td><%= contact.error_message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<%= link_to "My Contacts", contacts_path, :method => :get %><br/>
<%= link_to "Failed Contacts", failed_contacts_path, :method => :get %><br/>
<%= link_to "Add Contacts", new_contact_path, :method => :get %><br/>
<%= link_to "Uploaded files", csv_files_path, :method => :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br/>
  <%if user_signed_in?%>
  <nav class="margin-nav">
  <%= link_to "Home page", root_path, :method => :get %>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  </nav>
  <%end%>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>